// Content access layer. content.json is generated by scripts/build-content.mjs
// from the repository markdown (single source of truth).
import data from "@/content/content.json";

export interface Doc {
  id: string;
  file: string;
  area: string;
  category: string;
  title: string;
  subtitle: string;
  status: string;
  tags: string[];
  excerpt: string;
  words: number;
  readMin: number;
  raw: string;
}

export interface ContentBundle {
  generatedAt: string;
  total: number;
  byArea: Record<string, number>;
  docs: Doc[];
}

export const content = data as ContentBundle;
export const allDocs: Doc[] = content.docs;

export const docsByArea = (areaId: string): Doc[] =>
  areaId === "documentacao" ? allDocs : allDocs.filter((d) => d.area === areaId);

export const docById = (id: string): Doc | undefined => allDocs.find((d) => d.id === id);

export const countByArea = (areaId: string): number => docsByArea(areaId).length;

export const categoriesOf = (docs: Doc[]): string[] =>
  Array.from(new Set(docs.map((d) => d.category)));

export function searchDocs(q: string): Doc[] {
  const t = q.trim().toLowerCase();
  if (!t) return [];
  return allDocs
    .filter((d) =>
      (d.title + " " + d.subtitle + " " + d.excerpt + " " + d.category + " " + d.raw)
        .toLowerCase()
        .includes(t)
    )
    .slice(0, 12);
}
